- link:
    ~/.config/fish:
      force: true
      glob: true
      path: fish/*
    ~/.config/omf:
      force: true
      glob: true
      path: omf/*

- shell:
  - [apt install -y fish curl, Installing fish]
  - [chsh -s $(which fish) $USER, Setting fish as default shell] 
  - [curl -L 'https://get.oh-my.fish' | fish, Setting up omf]
  - [omf install, Installing omf packages]
